import ListSelectionScreen from "./pages/ListSelectionScreen";
import ListScreen from "./pages/ListScreen";
import { Routes, Route } from "react-router-dom";
import React, { useState, useEffect } from "react";
import "./css/App.css";

function App() {
  const [lists, setLists] = useState([
    {
      id: 0,
      name: "Weekly Shop",
      token: "0",
      list: [
        {
          id: 0,
          name: "banana",
          quantity: 1,
          unit: "litre",
          isCompleted: false,
        },
        { id: 1, name: "Eggs", quantity: 6, unit: "each", isCompleted: true },
      ],
    },
    {
      id: 1,
      name: "Shared list",
      token: "THISISAFAKETOKEN",
      list: [
        { id: 0, name: "Cheese", quantity: 7, unit: "kg", isCompleted: false },
        { id: 1, name: "Bread", quantity: 2, unit: "kg", isCompleted: false },
      ],
    },
    {
      id: 2,
      name: "Party food",
      token: "0",
      list: [
        { id: 0, name: "Pizza", quantity: 7, unit: "each", isCompleted: false },
        {
          id: 1,
          name: "cucumber",
          quantity: 2,
          unit: "kg",
          isCompleted: false,
        },
      ],
    },
    {
      id: 3,
      name: "Bulk Stock-up",
      token: "0",
      list: [
        { id: 0, name: "Rice", quantity: 5, unit: "kg", isCompleted: false },
        { id: 1, name: "Pasta", quantity: 3, unit: "kg", isCompleted: false },
        {
          id: 2,
          name: "Tomato Sauce",
          quantity: 4,
          unit: "each",
          isCompleted: false,
        },
        {
          id: 3,
          name: "Olive Oil",
          quantity: 2,
          unit: "litre",
          isCompleted: false,
        },
        { id: 4, name: "Flour", quantity: 2, unit: "kg", isCompleted: false },
        { id: 5, name: "Sugar", quantity: 2, unit: "kg", isCompleted: false },
        { id: 6, name: "Salt", quantity: 1, unit: "kg", isCompleted: false },
        {
          id: 7,
          name: "Pepper",
          quantity: 1,
          unit: "each",
          isCompleted: false,
        },
        {
          id: 8,
          name: "Tea Bags",
          quantity: 100,
          unit: "each",
          isCompleted: false,
        },
        { id: 9, name: "Coffee", quantity: 1, unit: "kg", isCompleted: false },
        {
          id: 10,
          name: "Milk",
          quantity: 4,
          unit: "litre",
          isCompleted: false,
        },
        { id: 11, name: "Butter", quantity: 2, unit: "kg", isCompleted: false },
        {
          id: 12,
          name: "Yogurt",
          quantity: 6,
          unit: "each",
          isCompleted: false,
        },
        {
          id: 13,
          name: "Chicken Breast",
          quantity: 3,
          unit: "kg",
          isCompleted: false,
        },
        {
          id: 14,
          name: "Beef Mince",
          quantity: 2,
          unit: "kg",
          isCompleted: false,
        },
        {
          id: 15,
          name: "Fish Fillets",
          quantity: 2,
          unit: "kg",
          isCompleted: false,
        },
        {
          id: 16,
          name: "Frozen Vegetables",
          quantity: 5,
          unit: "each",
          isCompleted: false,
        },
        {
          id: 17,
          name: "Frozen Chips",
          quantity: 2,
          unit: "kg",
          isCompleted: false,
        },
        {
          id: 18,
          name: "Cereal",
          quantity: 3,
          unit: "each",
          isCompleted: false,
        },
        { id: 19, name: "Oats", quantity: 2, unit: "kg", isCompleted: false },
        { id: 20, name: "Honey", quantity: 1, unit: "kg", isCompleted: false },
        { id: 21, name: "Jam", quantity: 2, unit: "each", isCompleted: false },
        {
          id: 22,
          name: "Peanut Butter",
          quantity: 1,
          unit: "kg",
          isCompleted: false,
        },
        {
          id: 23,
          name: "Tuna Cans",
          quantity: 10,
          unit: "each",
          isCompleted: false,
        },
        {
          id: 24,
          name: "Beans",
          quantity: 8,
          unit: "each",
          isCompleted: false,
        },
        {
          id: 25,
          name: "Chickpeas",
          quantity: 6,
          unit: "each",
          isCompleted: false,
        },
        {
          id: 26,
          name: "Lentils",
          quantity: 3,
          unit: "kg",
          isCompleted: false,
        },
        {
          id: 27,
          name: "Crisps",
          quantity: 5,
          unit: "each",
          isCompleted: false,
        },
        {
          id: 28,
          name: "Chocolate",
          quantity: 4,
          unit: "each",
          isCompleted: false,
        },
        {
          id: 29,
          name: "Biscuits",
          quantity: 6,
          unit: "each",
          isCompleted: false,
        },
        {
          id: 30,
          name: "Apples",
          quantity: 12,
          unit: "each",
          isCompleted: false,
        },
        {
          id: 31,
          name: "Oranges",
          quantity: 10,
          unit: "each",
          isCompleted: false,
        },
        { id: 32, name: "Grapes", quantity: 2, unit: "kg", isCompleted: false },
        {
          id: 33,
          name: "Bananas",
          quantity: 12,
          unit: "each",
          isCompleted: false,
        },
        {
          id: 34,
          name: "Potatoes",
          quantity: 5,
          unit: "kg",
          isCompleted: false,
        },
        { id: 35, name: "Onions", quantity: 3, unit: "kg", isCompleted: false },
        {
          id: 36,
          name: "Garlic",
          quantity: 5,
          unit: "each",
          isCompleted: false,
        },
        {
          id: 37,
          name: "Carrots",
          quantity: 2,
          unit: "kg",
          isCompleted: false,
        },
        {
          id: 38,
          name: "Broccoli",
          quantity: 3,
          unit: "each",
          isCompleted: false,
        },
        {
          id: 39,
          name: "Spinach",
          quantity: 2,
          unit: "each",
          isCompleted: false,
        },
        {
          id: 40,
          name: "Lettuce",
          quantity: 2,
          unit: "each",
          isCompleted: false,
        },
        {
          id: 41,
          name: "Tomatoes",
          quantity: 8,
          unit: "each",
          isCompleted: false,
        },
        {
          id: 42,
          name: "Cucumbers",
          quantity: 4,
          unit: "each",
          isCompleted: false,
        },
        {
          id: 43,
          name: "Peppers",
          quantity: 6,
          unit: "each",
          isCompleted: false,
        },
        {
          id: 44,
          name: "Mushrooms",
          quantity: 2,
          unit: "kg",
          isCompleted: false,
        },
        {
          id: 45,
          name: "Toilet Paper",
          quantity: 24,
          unit: "each",
          isCompleted: false,
        },
        {
          id: 46,
          name: "Kitchen Roll",
          quantity: 8,
          unit: "each",
          isCompleted: false,
        },
        { id: 47, name: "Soap", quantity: 6, unit: "each", isCompleted: false },
        {
          id: 48,
          name: "Shampoo",
          quantity: 2,
          unit: "each",
          isCompleted: false,
        },
        {
          id: 49,
          name: "Conditioner",
          quantity: 2,
          unit: "each",
          isCompleted: false,
        },
        {
          id: 50,
          name: "Toothpaste",
          quantity: 4,
          unit: "each",
          isCompleted: false,
        },
        {
          id: 51,
          name: "Toothbrushes",
          quantity: 4,
          unit: "each",
          isCompleted: false,
        },
        {
          id: 52,
          name: "Laundry Detergent",
          quantity: 2,
          unit: "kg",
          isCompleted: false,
        },
        {
          id: 53,
          name: "Fabric Softener",
          quantity: 2,
          unit: "litre",
          isCompleted: false,
        },
        {
          id: 54,
          name: "Dish Soap",
          quantity: 2,
          unit: "litre",
          isCompleted: false,
        },
        {
          id: 55,
          name: "Sponges",
          quantity: 6,
          unit: "each",
          isCompleted: false,
        },
        {
          id: 56,
          name: "Bin Bags",
          quantity: 30,
          unit: "each",
          isCompleted: false,
        },
        {
          id: 57,
          name: "Aluminium Foil",
          quantity: 1,
          unit: "each",
          isCompleted: false,
        },
        {
          id: 58,
          name: "Cling Film",
          quantity: 1,
          unit: "each",
          isCompleted: false,
        },
        {
          id: 59,
          name: "Baking Paper",
          quantity: 1,
          unit: "each",
          isCompleted: false,
        },
        {
          id: 60,
          name: "Hand Sanitiser",
          quantity: 2,
          unit: "each",
          isCompleted: false,
        },
        {
          id: 61,
          name: "Vitamins",
          quantity: 1,
          unit: "each",
          isCompleted: false,
        },
        {
          id: 62,
          name: "Painkillers",
          quantity: 2,
          unit: "each",
          isCompleted: false,
        },
        {
          id: 63,
          name: "Plasters",
          quantity: 1,
          unit: "each",
          isCompleted: false,
        },
        {
          id: 64,
          name: "Batteries",
          quantity: 12,
          unit: "each",
          isCompleted: false,
        },
        {
          id: 65,
          name: "Light Bulbs",
          quantity: 4,
          unit: "each",
          isCompleted: false,
        },
        {
          id: 66,
          name: "Tissues",
          quantity: 6,
          unit: "each",
          isCompleted: false,
        },
        {
          id: 67,
          name: "Hand Soap",
          quantity: 4,
          unit: "each",
          isCompleted: false,
        },
        {
          id: 68,
          name: "Shower Gel",
          quantity: 3,
          unit: "each",
          isCompleted: false,
        },
        {
          id: 69,
          name: "Deodorant",
          quantity: 2,
          unit: "each",
          isCompleted: false,
        },
        {
          id: 70,
          name: "Shaving Foam",
          quantity: 1,
          unit: "each",
          isCompleted: false,
        },
        {
          id: 71,
          name: "Razor Blades",
          quantity: 8,
          unit: "each",
          isCompleted: false,
        },
        {
          id: 72,
          name: "Nappies",
          quantity: 40,
          unit: "each",
          isCompleted: false,
        },
        {
          id: 73,
          name: "Baby Wipes",
          quantity: 5,
          unit: "each",
          isCompleted: false,
        },
        {
          id: 74,
          name: "Cat Food",
          quantity: 12,
          unit: "each",
          isCompleted: false,
        },
        {
          id: 75,
          name: "Dog Food",
          quantity: 12,
          unit: "each",
          isCompleted: false,
        },
        {
          id: 76,
          name: "Cat Litter",
          quantity: 10,
          unit: "kg",
          isCompleted: false,
        },
        {
          id: 77,
          name: "Dishwasher Tablets",
          quantity: 40,
          unit: "each",
          isCompleted: false,
        },
        {
          id: 78,
          name: "Bleach",
          quantity: 2,
          unit: "litre",
          isCompleted: false,
        },
        {
          id: 79,
          name: "Surface Cleaner",
          quantity: 2,
          unit: "litre",
          isCompleted: false,
        },
        {
          id: 80,
          name: "Spaghetti",
          quantity: 3,
          unit: "kg",
          isCompleted: false,
        },
        {
          id: 81,
          name: "Couscous",
          quantity: 2,
          unit: "kg",
          isCompleted: false,
        },
        { id: 82, name: "Quinoa", quantity: 2, unit: "kg", isCompleted: false },
        {
          id: 83,
          name: "Tortillas",
          quantity: 3,
          unit: "each",
          isCompleted: false,
        },
        {
          id: 84,
          name: "Salsa",
          quantity: 2,
          unit: "each",
          isCompleted: false,
        },
        {
          id: 85,
          name: "Soy Sauce",
          quantity: 1,
          unit: "litre",
          isCompleted: false,
        },
        {
          id: 86,
          name: "Vinegar",
          quantity: 1,
          unit: "litre",
          isCompleted: false,
        },
        {
          id: 87,
          name: "Mustard",
          quantity: 1,
          unit: "each",
          isCompleted: false,
        },
        {
          id: 88,
          name: "Mayonnaise",
          quantity: 1,
          unit: "each",
          isCompleted: false,
        },
        {
          id: 89,
          name: "Ketchup",
          quantity: 1,
          unit: "each",
          isCompleted: false,
        },
        {
          id: 90,
          name: "Hot Sauce",
          quantity: 1,
          unit: "each",
          isCompleted: false,
        },
        {
          id: 91,
          name: "Herbs",
          quantity: 6,
          unit: "each",
          isCompleted: false,
        },
        {
          id: 92,
          name: "Spices",
          quantity: 10,
          unit: "each",
          isCompleted: false,
        },
        {
          id: 93,
          name: "Stock Cubes",
          quantity: 12,
          unit: "each",
          isCompleted: false,
        },
        {
          id: 94,
          name: "Coconut Milk",
          quantity: 4,
          unit: "each",
          isCompleted: false,
        },
        {
          id: 95,
          name: "Curry Paste",
          quantity: 2,
          unit: "each",
          isCompleted: false,
        },
        {
          id: 96,
          name: "Noodles",
          quantity: 6,
          unit: "each",
          isCompleted: false,
        },
        {
          id: 97,
          name: "Energy Drinks",
          quantity: 6,
          unit: "each",
          isCompleted: false,
        },
        {
          id: 98,
          name: "Juice",
          quantity: 4,
          unit: "litre",
          isCompleted: false,
        },
        {
          id: 99,
          name: "Water Bottles",
          quantity: 12,
          unit: "each",
          isCompleted: false,
        },
      ],
    },
  ]);

  return (
    <main className="main-content">
      <Routes>
        <Route
          path="/"
          element={<ListSelectionScreen lists={lists} setLists={setLists} />}
        />
        <Route
          path="/list/:id"
          element={<ListScreen lists={lists} setLists={setLists} />}
        />
      </Routes>
    </main>
  );
}

export default App;
